# MySQL Database Configuration
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mariadb://localhost:3306/subway_db
db.username=subway
db.password=subway

# 참고사항:
# 1. db.password를 실제 본인 비밀번호로 변경하세요
# 2. db.username을 본인이 설정한 이름으로 변경하세요
# 3. MySQL 포트가 3306이 아니면 변경하세요
# 옆쪽 상단 DB버튼을 누르시고, properties를 누르시면 확인 가능합니다